**Assignment 1**


**Bond Forward Business**

The Payoff of a Bond Forward is defined as:

$$ V(T_{s}) = B(T_{s}; T_{s}, T_{m}) - K $$

where :
- $B(T_{s};·,·)$ is the bond price at settlement date $T_{s}$
- $K$ the strike agreed to make the contract at par at inception

The contract as Mark-to-Market value of:

$$V(t) = df^{csa}(t, T_{s}) · (B(t; T_{s}, T_{m} - K)$$

where:
- $df^{csa}$ is the CSA discounting
- $B(t; T_{s}, T_{m})$ is the time-t forward bond price

**You're the rates desk at bank A, a client wants to buy:**
- $1MUSD 1-year forward contract on UST mat., 10Y

**Q1: Motivation to enter a bond-forward contract**

A bond forward is an OTC derivative giving the buyer the obligation of buying the underlying bond at a pre-determined price (strike K) at a pre-determined date.

The benefits of entering a long bond forward contract on UST are multiples:
- In case of price appreciation of the underlying, the value of the forward will also increase. One could then sell the contract and generate a profit. For example if $V(t)$, the daily market-to-market value is positive, by selling, the client would generate a profit.

- Entering a forward contract on a UST is a market with very high liquidity. Since bond forward are settled in cash, high liquidity is valuable component of the transaction.

- A bond forward can also be used as hedging purposes. By locking-in the price of the underlying right now, the buyer would hedge himself if he expects interest rate to go down, causing bond prices to go up.

- The bond forward being an OTC derivative contract offers more flexibility for the client compared to standardized contracts such as bond futures.

- Since it is a derivative, it is also off-balance sheet and subject to less regulation strains.

- Finally, the motivation for entering a bond-forward contract is that the client expects the price at maturity $B(T_{s}; T_{s}, T_{m})$ to be greated than $K$, the agreed price.




**Q2: at t=0, the trading desk buy the spot, why?**

At t=0, the trading desk buys the spot bond to hedge itself against market fluctuations. Since the client is buying the bond-forward, the trading desk will have to deliver the bond at maturity. To avoid large losses (i.e. $B(T_{s}; T_{s}, T_{m}) >> K$) the trading desk can hold the bond for the time of the contract, sell it at maturity to hedge itself. Indeed, the spot price of the bond will converge to the forward price as it gets closer to maturity.


**Funding the bond position** 

To fund the bond position, meaning that the bond trader is short of cash, the bond trader would enter a repo transaction with the repo desk. 

At inception, the trading desk is buying the bond and lend it to the repo desk in exchange of cash. The transaction is rolled during the time of the forward transaction. Finally, at maturity the repo desk would give back the bond and receive its cash back plus interest (at the repo rate).

This strategy is known as cash-and-carry.

**Q3**


1) If we borrow $1 from repo desk, we have to pay back $1 plus interest at maturity
2) In a repo transaction, the seller (the one who delivers the security) is entitled to economic benefits including coupon payments. Coupon payments on UST are semi-annuals.

Therefore, we obtain:
$$B(0;T_{s}, T_{m}) = B(0;0, T_{m}) · (1 + R  - C)$$

With $C$ being the coupon rate pro-rated to the period of the transaction, $R$ the repo rate and  $B(0;0, T_{m})$ the cash lent by the repo desk at inception.

**Q4: MTM of the bond forward contract**

As presented above, the contract as Mark-to-Market value of:

$$V(t) = df^{csa}(t, T_{s}) · (B(t; T_{s}, T_{m} - K)$$

where:
- $df^{csa}$ is the CSA discounting
- $B(t; T_{s}, T_{m})$ is the time-t forward bond price

However, since the bond position is financed by a repo transaction, the discounting rate should be the repo rate R.

For the MTM value of the bond-forward, we finally obtain:

$$V(t) = exp^{-R(t, T_{s})} · (B(t; T_{s}, T_{m} - K)$$

with $R(t, T_{s})$ being the repo rate at time t.



**Q5: Market Risk**

In a repo transaction, the seller of the security is still subject to market risk. Entering the repo transaction hedged the market risk in the bond forward transaction. Indeed, the bond is purchased with borrowed fund via the repo transaction and is therefore pure arbitrage and risk free.

The strategy is known as cash and carry trade and consists of entering a long position in the cash market with a repo transaction and at the same time a short position in the future/forward market. The idea is then to deliver the underlying at expiration of the future/forward contract. The return of the transaction is the difference between the cost of the repo transaction in the cash market and the price of the forward contract. The rate of return is called the implied repo rate.

***Q5 risk neutral pricing**

The fundamental formula of risk neutral pricing states that the value of any contingent claim is simply the present value of expected future payoff discounted at the risk-free rate.

Following Q2-Q3, we found that the value of the bond-forward is simply the discounted value of future payoffs using the repo rate. Moreover, we found that financing the transaction in the repo market was risk free and can therefore be considered as an equivalent to risk neutral pricing.

**References**

- BoFa, The interaction between Repo and Bond Futures:
https://www.icmagroup.org/assets/documents/Events/Chris-Baron-BoA-ICMA-Conference-Bond-Basis.pdf

- CME Group, How CME RepoFunds Rate Futures Enhance Bond Basis Trading:
https://www.cmegroup.com/articles/whitepapers/how-cme-group-repofunds-rate-futures-enhance-bond-basis-trading.html

- DanskeBank, Information about Bond futures, bond forwards and bond options:
 https://danskebank.no/-/media/pdf/danske-bank/no/finansielle-instrumenter/bond-futures-bond-forwards-and-bond-options-en.pdf?rev=a457f31ee2544aeb86934590f55684bf&hash=346914C50FFBA418AADABB2E237AA9EB

- Koudry, The bond & money markets: strategy, trading, analysis

**Implementation of a simple interpolator**

In [ ]:
from abc import ABC, abstractmethod
import numpy as np

# define abstract class
class Interpolator(ABC):
    @abstractmethod
    def __init__(self, x, y):
        self.x = x
        self.y = y
        pass

    @abstractmethod
    def interpolate(x,y):
        pass

    @abstractmethod
    def gradient(x):
        pass

    @abstractmethod
    def integrate(x):
        pass


In [210]:
class oneD(Interpolator):

    
    def __init__(self, x, y):
        super().__init__(x, y)
        if len(x) != len(y):
            print("Length of x input is different from y")
        else:
        # Sort arrays based on x
            idx = np.argsort(x)
            self.x = np.array(x)[idx]
            self.y = np.array(y)[idx]
            return print(x , y)

    
    def interpolate(self, x_star):
        bins = self.x
        # Get indices of the bin
        bin_idx = np.digitize(x_star, bins, right=False)
        # To take into account values that falls outside of the left bound of the interval
        if bin_idx == 0:
            return self.y[0]
        # To take into account values that falls outside of the right bound of the interval     
        elif bin_idx >= len(bins):
            return self.y[-1]
        # To take into account what falls inside the intervals
        else:
            return self.y[bin_idx -1]


    def gradient(self, x_star):
        # Gradient is going to be a vector of zeros with a one at location of gradient of x
        # locate position using the interpolate function
        loc = self.interpolate(x_star)
        # generate a vector of zeros
        v = np.zeros(len(self.x))
        # At index location, input 1 to get the gradient
        v[loc] = 1
        return v
        

    def integrate(self, l, u):
        # Compute integral using np.trapz did not work
        x_right = np.append(self.x[1:], np.inf)
        lengths = np.maximum(0, np.minimum(u, x_right) - np.maximum(l, self.x))
        return np.sum(self.y * lengths)

    def gradient_integral(self, l, u):
        x_r = np.append(self.x[1:], np.inf)
        lengths = np.maximum(0, np.minimum(u, x_r) - np.maximum(l, self.x))
        return lengths

In [211]:
if __name__ == "__main__":
    f = oneD([2, 0, 5],[1, 3, 2])
    print(f.gradient(2))
    print(f.interpolate(0.5))  #works
    print(f.interpolate(10))   #works

[2, 0, 5] [1, 3, 2]
[0. 1. 0.]
3
2


Bump and revalue is a methodology to approximate greeks and PV01. It consists of adding a small increment to the price and recalculate the new price:

 $$\frac{V(x + \Delta x) - V(x)}{\Delta x}$$

In [216]:

def br_test(f, x=3, l=1, u=4, eps=1e-6):
    e_i = np.eye(len(f.y)) * eps  # Bump vectors
    num_p = [(oneD(f.x, f.y + e_i[i]).interpolate(x) - f.interpolate(x))/eps for i in range(len(f.y))]
    num_i = [(oneD(f.x, f.y + e_i[i]).integrate(l,u) - f.integrate(l,u))/eps for i in range(len(f.y))]
    
    print("gradient errors:", np.max(np.abs(f.gradient(x) - num_p)))
    print("gradient integral errors:", np.max(np.abs(f.gradient_integral(l,u) - num_i)))

br_test(f)

[0 2 5] [3.000001 1.       2.      ]
[0 2 5] [3.       1.000001 2.      ]
[0 2 5] [3.       1.       2.000001]
[0 2 5] [3.000001 1.       2.      ]
[0 2 5] [3.       1.000001 2.      ]
[0 2 5] [3.       1.       2.000001]
gradient errors: 8.22666379463044e-11
gradient integral errors: 2.795559339574538e-10


The gradient and gradient integral errors are very small compared to the bump and revalue methodology.